### ISSUE TITLE
Release LBC to public package repository

### ISSUE THREAD

**Issue by drnow4u** [Yolt-group/lovebird-commons#1]
As a developer I want to have possibility to download LBC package from public repository otherwise e.g. CFA is not possible to build. CFA and other project are still using not existing https://nexus.yolt.io/repository/public/

**Comment by drnow4u** [comment]
@mart1n-visser will you publish `security-utils` repository? The module `secrets-pipeline` has dependency on it.

**Comment by mart1n-visser** [comment]
Hi @drnow4u , unfortunately these are the only repo's that were salvaged, all others sources are removed. Sorry! Also there will be little to no maintenance on this codebase, so please fill a PR for any other improvements please!

**Comment by mart1n-visser** [comment]
Hi @drnow4u , unfortunately these are the only repo's that were salvaged, all others sources are removed. Sorry! Also there will be little to no maintenance on this codebase, so please fill a PR for any other improvements!

**Comment by drnow4u** [comment]
Hi @mart1n-visser, Thank you for information and rescue of the code!
